name: CICD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Client-Build-and-Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: check out the code

      - uses: mr-smithers-excellent/docker-build-push@v6
      - name: Build and Push Docker Image
        with:
          image: rajashekar1/social-media
          tags: client
          registry: docker.io
          dockerfile: ./client/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

  Server-Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check out the code

      - uses: mr-smithers-excellent/docker-build-push@v6
      - name: Build and Push Docker Image
        with:
          image: rajashekar1/social-media
          tags: server
          registry: docker.io
          dockerfile: ./server/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
