name: CICD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Client-Build-and-Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: rajashekar1/sociopedia
          tags: client
          registry: docker.io
          dockerfile: ./client/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

  Server-Build-and-Deploy:
    runs-on: ubuntu-latest
    needs: Client-Build-and-Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: rajashekar1/sociopedia
          tags: server
          registry: docker.io
          dockerfile: ./server/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Deploy to Aws ECR
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: image-name
          registry: [aws-account-number].dkr.ecr.[region].amazonaws.com
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        continue-on-error: true
      - name: Send Failure EMail
        if: failure()
        uses : dawidd6/action-send-mail@v3
        with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
        body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}.
        to: 999@gmail.com
        from: raja@gmail.com.com
